### ISSUE TITLE
rrd_slam not compiling

### ISSUE THREAD

**Issue by ashish786** [jaehak/rrd_slam#1]
Hi, I performed the steps as given in Install_ubuntu.txt. After doing "rosmake lsd_slam" lsd_slam_viewer package is built but lsd_slam_core is not built. So i created a directory 'build' inside lsd_slam_core package and typed the following command inside 'build' directory..
1. ccmake ..
changed  OpenCV_CONFIG_PATH /home/nitesh/Devel/share/OpenCV and OpenCV_DIR /home/nithesh/Devel/share/OpenCV and press 'c'. This is what i got : 
 [rosbuild] Building package lsd_slam_core

 [rosbuild] using multiarch 'x86_64-linux-gnu' for finding Boost

 [rosbuild] Including /opt/ros/indigo/share/roslisp/rosbuild/roslisp.cmake

 [rosbuild] Including /opt/ros/indigo/share/roscpp/rosbuild/roscpp.cmake

 [rosbuild] Including /opt/ros/indigo/share/rospy/rosbuild/rospy.cmake

 MSG: gencfg_cpp on:LSDDebugParams.cfg

 [gendeps] Finding dependencies for /home/nitesh/rosbuild_ws/package_dir/lsd_slam/lsd_slam_core/cfg/LSDDebugParams.cfg

 MSG: gencfg_cpp on:LSDParams.cfg

 [gendeps] Finding dependencies for /home/nitesh/rosbuild_ws/package_dir/lsd_slam/lsd_slam_core/cfg/LSDParams.cfg

Then after exiting with 'e'
I pressed 'g' which gave the following error:
CMake Warning at /opt/ros/indigo/share/ros/core/rosbuild/public.cmake:509 (add_executable):
   Cannot generate a safe linker search path for target dataset because files
   in some directories may conflict with libraries in implicit directories:

     link library [libopencv_videostab.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_video.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_superres.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_stitching.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_photo.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_ocl.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_objdetect.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_ml.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_legacy.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_imgproc.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_highgui.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_gpu.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_flann.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_features2d.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_core.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
       /usr/local/lib
     link library [libopencv_contrib.so.2.4.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:

Please let me know what i am doing wrong.

**Comment by jaehak** [comment]
It appears warnings are related to the new OpenCV paths. How is the compiling going after ccmake?

**Comment by ashish786** [comment]
This is what i got after compiling using ccmake and pressing 'c' : 
     

[rosbuild] using multiarch 'x86_64-linux-gnu' for finding Boost

[rosbuild] Including /opt/ros/indigo/share/roslisp/rosbuild/roslisp.cmake

[rosbuild] Including /opt/ros/indigo/share/roscpp/rosbuild/roscpp.cmake

[rosbuild] Including /opt/ros/indigo/share/rospy/rosbuild/rospy.cmake

MSG: gencfg_cpp on:LSDDebugParams.cfg

[gendeps] Finding dependencies for /home/nitesh/rosbuild_ws/package_dir/lsd_slam/lsd_slam_core/cfg/LSDDebugParams.cfg

MSG: gencfg_cpp on:LSDParams.cfg

[gendeps] Finding dependencies for /home/nitesh/rosbuild_ws/package_dir/lsd_slam/lsd_slam_core/cfg/LSDParams.cfg

**Comment by ashish786** [comment]
After getting error in ccmake, i again tried the command rosmake. This time rosmake build both the component ie lsd_slam_core and lsd_slam_viewer. 

Is is ok to proceed with this or ccmake is compulsory.

**Comment by jaehak** [comment]
OK
